# https://taskfile.dev

version: "3"

# vars:
# GREETING: Hello, World!

tasks:
  convert-reports:
    vars:
      convert_command: >
        ls ~/Documents/work/ipu/**/*
        | where type == file
        | $in.name
        | each { path parse }
        | where extension == docx
        | each { pandoc --wrap=none $"($in.parent)/($in.stem).($in.extension)" -o $"~/Documents/work/12_sem/thesis/ignored/($in.stem).typ"}
    cmds:
      - nu -c '{{.convert_command}}'
